# Generated by Django 5.0.2 on 2024-03-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_convidado_presente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convidado',
            name='rg',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
