# Generated by Django 5.0.2 on 2024-03-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_convidado_rg'),
    ]

    operations = [
        migrations.AddField(
            model_name='convidado',
            name='presenca',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='convidado',
            name='presente',
            field=models.CharField(max_length=5),
        ),
    ]
