# Generated by Django 5.0.2 on 2024-03-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_area_item2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item2',
            name='area',
        ),
        migrations.AlterField(
            model_name='outros',
            name='item',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='areadeservico',
            name='item',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='banheiro',
            name='item',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='item',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cozinha',
            name='item',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Item2',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
