# Generated by Django 5.0.2 on 2024-03-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_item2_area_alter_outros_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convidado',
            name='checkbox_selecionado',
            field=models.BooleanField(default=False),
        ),
    ]
